import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import CSVReader from '@/components/CSVp'
import { useEffect, useState } from 'react'
import { csvToObject } from '@/hooks/csvParser'


export default function Home() {
  const [users, setUsers]: any = useState([])
  const  [loading, setLoading] = useState(false)

  const handleUpload = async (values: any) => {
    const data: any = await csvToObject(values.data)
    setUsers(data)
  }

  useEffect(() => {
    async function add() {
      try {
        setLoading(true)

        const response = await fetch(
          'http://localhost:3002/webhook/members/ui/add',
          {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify(users)
          },
        )

        if (!response.ok) {
          throw new Error(`Failed to send request: ${response.status}`)
        }
        const data = await response.json()

        
        return data 
      } catch (err) {
        console.error(err)
      }
    }

    add()
      .then(() => {
        setLoading(false)

      })
      .catch((err) => console.error('pile bobo', err))
  }, [users])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <CSVReader onDrop={handleUpload} />
            <p> {loading ? 'loading. . .' : 'Done!'} </p>
          </div>
       
       
        </div>

      
      </main>
    </>
  )
}
